name: Build LEDE PVE X86

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            clang \
            flex \
            bison \
            g++ \
            gawk \
            gettext \
            git \
            libncurses-dev \
            libssl-dev \
            python3 \
            python3-setuptools \
            rsync \
            unzip \
            zlib1g-dev


      - name: Clone LEDE
        run: |
          git clone https://github.com/coolsnowwolf/lede.git openwrt


      - name: Add PassWall
        run: |
          cd openwrt

          echo "src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git;main" >> feeds.conf.default

          echo "src-git passwall_luci https://github.com/Openwrt-Passwall/openwrt-passwall.git;main" >> feeds.conf.default


      - name: Update feeds
        run: |
          cd openwrt

          ./scripts/feeds update -a

          ./scripts/feeds install -a


      - name: Configure
        run: |
          cd openwrt

          make defconfig

          cat >> .config <<EOF

CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_DEVICE_generic=y

CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-app-passwall=y

CONFIG_PACKAGE_dnsmasq-full=y
CONFIG_PACKAGE_smartdns=y

CONFIG_PACKAGE_kmod-virtio=y
CONFIG_PACKAGE_kmod-virtio-net=y
CONFIG_PACKAGE_kmod-virtio-scsi=y

CONFIG_PACKAGE_kmod-tun=y
CONFIG_PACKAGE_iptables-mod-tproxy=y

CONFIG_PACKAGE_ca-bundle=y
CONFIG_PACKAGE_ca-certificates=y

EOF

          make defconfig


      - name: Compile
        run: |
          cd openwrt
          make -j$(nproc) V=s


      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: LEDE-PVE-X86
          path: openwrt/bin/targets/x86/64/*
